export ZSH="$HOME/.oh-my-zsh"
export PATH=$HOME/.local/bin:$PATH
export LIBVIRT_DEFAULT_URI="qemu:///system"
export EDITOR='nvim'

source ~/.local/bin/check-os.zsh
source $ZSH/oh-my-zsh.sh
ZSH_THEME="agnoster"

# oh-my-zsh plugins
plugins=(git fnm)

COMPLETION_WAITING_DOTS="true"

if [[ "$OS_TYPE" == *"Fedora"* ]]; then
    source /usr/share/fzf/shell/key-bindings.zsh
    alias find="fd"
    alias cat="bat"
    alias pcat="bat -p"
elif [[ "$OS_TYPE" == *"Ubuntu"* ]]; then
    source /usr/share/doc/fzf/examples/key-bindings.zsh
    alias find="fdfind"
    alias cat="batcat"
    alias pcat="batcat -p"
else
    echo "!! This system is neither Fedora nor Ubuntu !!"
fi


alias nvm="fnm"
alias vim="nvim"
alias pbcopy="wl-copy"
alias pbpaste="wl-paste"
alias df="duf"
alias du="dust -d 1"
alias grep="rg"
alias ls="exa"
alias free="free -h"
alias dc="docker compose"

# custom
alias ls-latest="exa -la --sort=modified --reverse --color=always | head -n 11"
alias cdp="cd ~/projects"

eval "$(fnm env)"
