export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

COMPLETION_WAITING_DOTS="true"

plugins=(git fnm)

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

source /usr/share/doc/fzf/examples/key-bindings.zsh

alias cat="batcat"
alias cat="batcat -p"

alias nvm="fnm"
alias vim="nvim"
alias pbcopy="xclip -selection clipboard"
alias cdp="cd ~/projects"
alias df="duf"
alias du="dust -d 1"
alias grep="rg"
alias ls="exa"

eval "$(fnm env --use-on-cd)"

export PATH=$HOME/.local/bin:$PATH
