#!/usr/bin/env bash

# set wallpaper for default and dark mode 

file=$(readlink -f $1)
gsettings set org.gnome.desktop.background picture-uri "file://${file}"
gsettings set org.gnome.desktop.background picture-uri-dark "file://${file}"
